import type { NextPage, NextComponentType } from "next";
import Head from "next/head";

import styles from "../styles/Login.module.css";

import logo from "../assets/logo.svg";
import LumiaTextField from "../components/common/LumiaTextField";
import { Button,Box } from "@mui/material";
import { NextRouter, useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div style={{ marginTop: "50px" }}></div>
      <LoginPageColumn />

      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main> */}

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

function LoginPageColumn({}) {
  const router = useRouter();
  return (
    <div className={styles.login_column}>
      <img src={logo.src} className={styles.logo} />
      <h1 className={styles.lumia_title}>Lumia</h1>
      <div className={styles.top_rounded_container}>
        <h2 className={styles.welcome_back}>Welcome back</h2>
        <LumiaTextField
          className={styles.email_textfield}
          label={"email"}
          id={"email"}
          defaultValue={""}
          width={"80%"}
        />
        <Box height={10}/>
        <LumiaTextField
          className={styles.email_textfield}
          label={"password"}
          id={"password"}
          defaultValue={""}
          width={"80%"}
        />
        <p className={styles.forgot_password}>Forgot password?</p>
        <Button
          className={styles.login_button}
          variant="contained"
          sx={{
            width: "80%",
            height: "50px",
            margin: "0px",
            backgroundColor: "#EEBBC3",
            color: "#222845",
          }}
          onClick={() => {
            console.log("clicked");
            router.push("/home");
          }}
        >
          Login
        </Button>
        <p className={styles.sign_up_text}>Dont have an account? Create one</p>
      </div>
    </div>
  );
}

export default Home;
